name: qiita_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # json ⇄ model
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  build_runner: ^2.1.8
  # api通信
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  # freezed
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  # state
  provider: ^6.0.2
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
